name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
      prerelease:
        description: 'Is this a prerelease? (true/false)'
        required: true
        default: 'false'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 构建 Windows 版本
        run: echo "Building Windows version..."
        # 假设这里有构建步骤，最终生成 Fanqie-Novel-Downloader-Windows.zip
      - name: 上传 Windows 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: Fanqie-Novel-Downloader-Windows.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 构建 MacOS 版本
        run: echo "Building macOS version..."
        # 假设这里有构建步骤，最终生成 Fanqie-Novel-Downloader-MacOS.zip
      - name: 上传 MacOS 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: Fanqie-Novel-Downloader-MacOS.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 构建 Linux 版本
        run: echo "Building Linux version..."
        # 假设这里有构建步骤，最终生成 Fanqie-Novel-Downloader-Linux.zip
      - name: 上传 Linux 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: Fanqie-Novel-Downloader-Linux.zip

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: 检出代码并获取完整提交历史
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取所有提交历史

      - name: 下载 Windows 构建产物
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: 下载 MacOS 构建产物
        uses: actions/download-artifact@v4
        with:
          name: macos-build

      - name: 下载 Linux 构建产物
        uses: actions/download-artifact@v4
        with:
          name: linux-build

      - name: 获取最近的提交信息
        run: |
          COMMITS=$(git log -5 --pretty=format:"- %s (%h)")
          echo "COMMIT_MESSAGES<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          name: Fanqie Novel Downloader ${{ github.event.inputs.version }}
          body: |
            Fanqie Novel Downloader ${{ github.event.inputs.version }} Release

            ### 更新内容
            ${{ env.COMMIT_MESSAGES }}

            ### Features
            - Download novels from Fanqie and export as TXT or EPUB format
            - Support multi-threaded downloading for acceleration
            - Automatically fix ebooklib.epub module import issues

            ### Downloads
            - Windows: Fanqie-Novel-Downloader-Windows.zip
            - macOS: Fanqie-Novel-Downloader-MacOS.zip
            - Linux: Fanqie-Novel-Downloader-Linux.zip
          files: |
            Fanqie-Novel-Downloader-Windows.zip
            Fanqie-Novel-Downloader-MacOS.zip
            Fanqie-Novel-Downloader-Linux.zip
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
