name: 在线下载小说

on:
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      novel_id:
        description: '小说ID (从番茄小说URL中获取)'
        required: true
      threads:
        description: '下载线程数 (1-10, 如果大于10将自动设置为10)'
        required: true
        default: '5'
      format:
        description: '输出格式'
        required: true
        type: choice
        options:
          - epub
        default: 'epub'

permissions:
  contents: read  # 允许读取仓库内容
  actions: write  # 允许上传构建产物

jobs:
  download-novel:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 确保cookie.json存在
        run: |
          if [ ! -f "./cookie.json" ]; then
            echo '""' > "./cookie.json"
          fi
      
      - name: 安装虚拟显示服务
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
      
      - name: 检查线程数
        run: |
          threads=${{ github.event.inputs.threads }}
          if [ $threads -gt 10 ]; then
            echo "线程数不能大于10，自动设置为10"
            threads=10
          fi
          echo "THREADS=$threads" >> $GITHUB_ENV
      
      - name: 下载小说
        run: |
          echo "开始下载小说..."
          python download_novel.py "${{ github.event.inputs.novel_id }}" "${{ github.event.inputs.format }}" "$THREADS"
      
      - name: 压缩下载结果
        run: |
          cd novel_output && zip -r ../novel_files.zip *
      
      - name: 上传下载结果
        uses: actions/upload-artifact@v4
        with:
          name: novel-${{ github.event.inputs.novel_id }}-${{ github.event.inputs.format }}
          path: novel_files.zip
          retention-days: 7  # 文件保存7天
      
      - name: 提供下载信息
        run: |
          echo "✅ 小说下载完成！"
          echo "请点击上方 'Summary' 标签，然后在 'Artifacts' 部分下载小说文件。"
          echo "文件保存期限为7天。"
